[package]
name = "day07"
version = "0.1.0"
authors = ["Steve Chuck <schuck017@gmail.com>"]
edition = "2018"

[dependencies]
aoc2020 = { path = ".." }
color-eyre = "0.5.8"
structopt = "0.3.20"
thiserror = "1.0.22"
itertools = "0.9.0"
parse-display = "0.4.0"
regex = "1"